# docker-compose.yml

version: "3.8"
services:
  db:
    image: postgres:14
    restart: always
    environment:
      - POSTGRES_USER=polash
      - POSTGRES_PASSWORD=polash
    volumes:
      - db:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  nestjs:
    # it has a docer file inside apps/api dir
    build: ./apps/server
    restart: always
    ports:
      - "4000:4000"
    depends_on:
      - db

  nextjs:
    # it has a docer file inside apps/client dir
    build: ./apps/client
    restart: always
    ports:
      - "3000:3000"
    depends_on:
      - nestjs

volumes:
  db:
